# Generated by Django 5.2.4 on 2025-08-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='Main.employee')),
                ('requested_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.department')),
            ],
        ),
    ]
